services:
  - type: web
    name: befitoutfit-backend
    env: node
    buildCommand: |
      npm install
      npx prisma generate
      mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD < prisma/init.sql
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: befitoutfit-db
          property: connectionString
          transform: |
            const url = new URL(value);
            return `mysql://${url.username}:${url.password}@${url.hostname}:${url.port}${url.pathname}`;
      - key: DB_HOST
        fromDatabase:
          name: befitoutfit-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: befitoutfit-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: befitoutfit-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 1
    timeout: 120

databases:
  - name: befitoutfit-db
    databaseName: befitoutfit
    plan: free 