services:
  - type: web
    name: befitoutfit-backend
    env: node
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: befitoutfit-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 1
    timeout: 120

databases:
  - name: befitoutfit-db
    databaseName: befitoutfit
    plan: free 